# Generated by Django 6.0.6 on 2026-06-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plushies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plushie',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
