# Generated by Django 6.0.5 on 2026-06-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
