# Generated by Django 6.0.5 on 2026-06-10 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
